export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER"
export const FETCH_BOARD_MEMBERS = "FETCH_BOARD_MEMBERS"

export const FETCH_BOARD_TASKS = "FETCH_BOARD_TASKS"
export const CREATE_BOARD_TASK = "CREATE_BOARD_TASK"
export const UPDATE_BOARD_TASK = "UPDATE_BOARD_TASK"
export const DELETE_BOARD_TASK = "DELETE_BOARD_TASK"

export const CREATE_BOARD_COLUMN = "CREATE_BOARD_COLUMN"
